### ISSUE TITLE
addCallback

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/ShowUnderline#2]
I experienced this with several plugins, but @guidoferreyra found this plugin as an example, so I open an issue here, even though it’s a bit more general.

When you have more than one plugin installed, which use
`Glyphs.addCallback(*function name*, DRAWBACKGROUND)`
they conflict with each other. All of the plugins with the callback fail to work then. Normal reporterPlugins keep working.

According to the Glyphs documentation »The function names are used to add/remove the functions to the hooks, so make sure to use unique function names.« But it seems that the added `DRAWBACKGROUND` is not uniquely enough?! Is that possible to make that happen?

The passed in function names are definitely not the same. And reporter plugins don’t conflict wich each other even though they add themselves to the hook as well. No?

I’d love to find a solution, because I currently need to uninstall all other plugins with an `addCallback` to use another one of that group.

Thanks so much in advance!

**Comment by schriftgestalt** [comment]
What version of Glyphs are you using? 
Can you send me two sample plugins/scripts, that do not work at the same time?

**Comment by Mark2Mark** [comment]
From what I heard it’s this »ShowUnderline« together with »Skedge«. I didn’t check this particular couple myself (yet).

Will do so and come back here then. I’ll also send you some files then.

Glyphs Versions are between 1060 … 1064 and 1073. Got all those parallely, no cutting edge ATM.

**Comment by schriftgestalt** [comment]
Can you try the latest stable version?

**Comment by Mark2Mark** [comment]
Okay, checked with Glyphs build 1075:

If ShowUnderline is installed (doesn’t need to be active), then »Skedge« doesn’t draw to the View anymore. Both plugins installed via the Plugin Manager. [Skedge](https://github.com/Mark2Mark/Skedge) works when ShowUnderline is not installed.

**Comment by schriftgestalt** [comment]
I was testing with the wrong version. 
I fixed it.

**Comment by Mark2Mark** [comment]
In which version can I test this?

And I’m curious: what did you change? :)

**Comment by schriftgestalt** [comment]
I the next update.
